### ISSUE TITLE
ModuleNotFoundError: No module named 'vision_transformer'

### ISSUE THREAD

**Issue by zussini** [qianqianwang68/omnimotion#19]
I have installed vision_transformer from this site:
https://github.com/google-research/vision_transformer/tree/main

but I still get the error:
ImportError: cannot import name 'RAFT' from 'raft' (/home/piotr/anaconda3/envs/omnimotion/lib/python3.8/site-packages/raft/__init__.py)
Traceback (most recent call last):
  File "extract_dino_features.py", line 27, in <module>
    import vision_transformer as vits
ModuleNotFoundError: No module named 'vision_transformer'

Do you have any idea what did I wrong ? 
I am trying to preprocess my own sequences.

**Comment by qianqianwang68** [comment]
Did you do this step https://github.com/qianqianwang68/omnimotion/tree/main/preprocessing#preparation?
What command did you run and what does the file structure look like?

**Comment by zussini** [comment]
Partially :)
I mean I have changed a bit to sth like:

cd preprocessing/

cp exhaustive_raft.py filter_raft.py chain_raft.py RAFT/;
### with below line I had problems as I did not find any
download_models.sh should I prepare it by myself ?

cd RAFT; ./download_models.sh; cd ../

cp extract_dino_features.py dino/

the sequence folder is in the preprocessing folder

regards

Piotr


wt., 29 sie 2023 o 22:39 Qianqian Wang ***@***.***>
napisał(a):

**Comment by zussini** [comment]
oh and the error was after executing this command:
python main_processing.py --data_dir /absolute-dir-to-sequence/ --chain

**Comment by qianqianwang68** [comment]
not exactly sure why. If you go to the RAFT folder and run `python exhaustive_raft.py --data_dir /absolute-dir-to-sequence/`, do you get the same error?

**Comment by zussini** [comment]
when I run this python exhaustive_raft.py --data_dir /absolute-dir-to-sequence/
I get only error about RAFT
Traceback (most recent call last):
  File "exhaustive_raft.py", line 18, in <module>
    from raft import RAFT
ImportError: cannot import name 'RAFT' from 'raft' (/home/piotr/anaconda3/envs/omnimotion/lib/python3.8/site-packages/raft/__init__.py)

**Comment by zussini** [comment]
Yes, they were empty. I will follow suggestions and let know.
Thanks!

śr., 30 sie 2023, 19:56 użytkownik Qianqian Wang ***@***.***>
napisał:

**Comment by zussini** [comment]
I have reiterated the whole process on another machine and it went smoothly as it seems. 
If I will find what was the problem on the other machine I will get back with the feedback. Probably some error on my side, 
but will try to find out.

Best Regards
