### ISSUE TITLE
CUDA out of memory when running the train.py

### ISSUE THREAD

**Issue by SongPool** [qianqianwang68/omnimotion#22]
This computer has 10 GPU and still out of memory after enabling distributed training
I h set args.distributed=1,  and 
os. environ[' RANK'] = '0'
os. environ[' WORLD_SIZE'] = '1'ave
os. environ[' MASTER ADDR'] = 'Locathost '
os. environ[' MASTER_PORT'] = '7356'

/home/user/disk1/user/anaconda3/envs/omni/bin/python /home/user/tapir_2022_10_19/pycharm-community-2021.1.2/plugins/python-ce/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 35291 --file /home/user/disk1/user/omnimotion/train.py
Connected to pydev debugger (build 211.7442.45)
Backend TkAgg is interactive backend. Turning interactive mode on.
optimizing for tennis...
 output is saved in out/default_tennis
No ckpts found, from scratch...
Traceback (most recent call last):
  File "/home/user/tapir_2022_10_19/pycharm-community-2021.1.2/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/user/tapir_2022_10_19/pycharm-community-2021.1.2/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/user/disk1/user/omnimotion/train.py", line 113, in <module>
    train(args)
  File "/home/user/disk1/user/omnimotion/train.py", line 84, in train
    trainer.train_one_step(step, batch)
  File "/home/user/disk1/user/omnimotion/trainer.py", line 540, in train_one_step
    loss, flow_data = self.compute_all_losses(batch,
  File "/home/user/disk1/user/omnimotion/trainer.py", line 447, in compute_all_losses
    out = self.get_blending_weights(x1s_canonical_samples)
  File "/home/user/disk1/user/omnimotion/trainer.py", line 256, in get_blending_weights
    color, density = self.get_canonical_color_and_density(x_canonical)
  File "/home/user/disk1/user/omnimotion/trainer.py", line 245, in get_canonical_color_and_density
    out_canonical = self.color_mlp(x_canonical)
  File "/home/user/disk1/user/anaconda3/envs/omni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/disk1/user/anaconda3/envs/omni/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/user/disk1/user/anaconda3/envs/omni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/disk1/user/omnimotio
![GWCIBXZN0Q`CLLNMS2IP%L8](https://github.com/qianqianwang68/omnimotion/assets/109713554/93e8fb01-2ff0-48d1-891e-90c979048545)
n/networks/mfn.py", line 40, in forward
    out = self.filters[i](x) * self.linear[i - 1](out)
  File "/home/user/disk1/user/anaconda3/envs/omni/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/disk1/user/omnimotion/networks/mfn.py", line 110, in forward
    return torch.sin(self.linear(x)) * torch.exp(-0.5 * D * self.gamma[None, :])
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 10.76 GiB total capacity; 8.45 GiB already allocated; 92.12 MiB free; 8.47 GiB reserved in total by PyTorch)
python-BaseException

Process finished with exit code 1

**Comment by Ryandonofrio3** [comment]
Yes having same issue. Not sure much can be done. Getting access to local compute cluster today to try and rectify

**Comment by qianqianwang68** [comment]
Hi, what command did you use to run the distributed training? It should be `python -m torch.distributed.launch --nproc_per_node={NUM_GPUs} train.py ...`. At the same time, you should try to reduce the number of pts and chunk size. The total number of points trained equals NUM_GPUs * args.num_pts, which means that num_pts can be reduced to 1/NUM_GPUs of the total number of points desired.

**Comment by psandovalsegura** [comment]
I was having the same issue, and noticed only one GPU was getting used before the OOM. What fixed it for me was adding this line in train.py:
```
if args.distributed:
        args.local_rank = int(os.environ['LOCAL_RANK']) # Add this line!
        torch.cuda.set_device(args.local_rank)
        torch.distributed.init_process_group(backend="nccl", init_method="env://")
        synchronize()
        ...
```
Because in config.py, `args.local_rank` is set to 0 and this rank is used in trainer.py. This is also explained in the torch.distributed.launch logs:
```
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions
```

Overall, I run the following to start training on multiple GPUs:
```
python -m torch.distributed.launch --nproc_per_node=${WORLD_SIZE} train.py \
       --config configs/default.txt --data_dir $SEQUENCE_DIR --save_dir $OUTPUT_DIR \
       --distributed 1 --num_pts 64
```

I also:
- Set `--num_pts 64` since I am training on 4 GPUs
- Increased CPU memory (I was getting `error: Detected 5 oom_kill events in StepId=1644314.batch. Some of the step tasks have been OOM Killed.` errors otherwise)
