### ISSUE TITLE
Reporting mistakes during training

### ISSUE THREAD

**Issue by MrWhite928** [qianqianwang68/omnimotion#39]
When running a command
python train.py --config configs/default.txt --data_dir {sequence_directory}
Even when using the processed data you provided, the following error will be reported
No ckpts found, from scratch...
Traceback (most recent call last):
  File "train.py", line 105, in <module>
    train(args)
  File "train.py", line 81, in train
    for batch in data_loader:
  File "/home/BHX/anaconda3/envs/omnimotion/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/BHX/anaconda3/envs/omnimotion/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/home/BHX/anaconda3/envs/omnimotion/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/home/BHX/anaconda3/envs/omnimotion/lib/python3.8/site-packages/torch/_utils.py", line 434, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/BHX/anaconda3/envs/omnimotion/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/BHX/anaconda3/envs/omnimotion/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/BHX/anaconda3/envs/omnimotion/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/BHX/omnimotion/omnimotion/loaders/raft.py", line 123, in __getitem__
    count_map = imageio.imread(os.path.join(self.seq_dir, 'count_maps', img_name1.replace('.jpg', '.png')))
  File "/home/BHX/anaconda3/envs/omnimotion/lib/python3.8/site-packages/imageio/__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "/home/BHX/anaconda3/envs/omnimotion/lib/python3.8/site-packages/imageio/v2.py", line 360, in imread
    result = file.read(index=0, **kwargs)
  File "/home/BHX/anaconda3/envs/omnimotion/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 231, in read
    image = self._apply_transforms(
  File "/home/BHX/anaconda3/envs/omnimotion/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 312, in _apply_transforms
    image.mode = desired_mode
AttributeError: can't set attribute

**Comment by qianqianwang68** [comment]
could you check if you have the complete training data and the path is correct?

**Comment by MrWhite928** [comment]
Incompatibility between Pillow 10.1.0 and imageio causes this error, pip install Pillow == 10.0 can fix it.
